---
title: "2015 Annual Activities Report"
author: "Dominic LaRoche"
date: "April 28, 2016"
output: word_document
---

During my third year of tenure on the National Science Foundation (NSF) Graduate Research Fellowship Program (GRFP) I have completed my required coursework for my PhD, passed my qualifying exams, and begun work on my dissertation. In the past year I have given two guest lectures in statistics, one to an undergraduate introductory statistics course and another to a graduate level applied statistics course.  I also presented on a method for translational statistics at the weekly biostatistics seminar. I also attended several statistical workshops at the International Conference of Health Policy Statistics in Providence, RI where I presented a poster. To continue my broader impacts I have participated in a high school outreach program designed to encourage disadvantaged high school juniors and seniors to pursue a higher education degree in the statistical sciences.  I have also created a statistical software package for the US Fish and Wildlife Service (USFWS) that enables them to calculate habitat suitability for the critically endangered Masked Bobwhite Quail.

After my unsuccessful attempt at the qualifying exam in my previous department I applied and was accepted into the PhD program in Biostatistics at the University of Arizona.  I was able to keep my adviser as he is a member of both departments and much of my coursework transferred into the new department.  I took and passed the PhD qualifying exam in June and finished up coursework in the fall semester.  I have also began work on my dissertation evaluating the impact of compositional data structures in RNA sequencing using next generation sequencing technology.  I will be working heavily on my dissertation in the coming year and hope to be ready to defend by April of 2017. 

I have developed my teaching skills by preparing and giving two guest lectures in statistics courses.  I gave a lecture in the fall semester to a graduate applied statistics course on modern variable selection methods.  In the spring I gave a lecture on the construction and interpretation of confidence intervals to a undergraduate introductory statistics course.  In an effort to encourage under-privileged high school students to pursue degrees in the statistical sciences I participated in an outreach program initiated by a fellow graduate student.  As part of this program I visited two high schools  in southern Arizona which serve primarily poor and minority students and gave interactive presentations to 4 classes in which we tried to encourage students to pursue a college degree in the statistical sciences and fielded questions about college, careers in science, and graduate school.  I also collaborated with USFWS scientists to translate my previous work on the critically endangered Masked Bobwhite Quail into a R software package which they can then use to improve management of the quail on both the Buenos Aries National Wildlife Refuge and release sites in Mexico.
